name: Update Version on merge
on:
  pull_request:
    types:
      - closed
    branches:
      - create-release-from-label

jobs:
  update-version:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check label
        id: check_label
        run: |
          first_label=$(jq -r '.pull_request.labels[0].name' <<<'${{ toJson(github.event) }}')
          echo "::set-output name=LABEL_NAME::$first_label"
          echo "LABEL=$first_label" >> $GITHUB_ENV
          echo "Label is $first_label"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        id: install-dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup the git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Update Label for Patch
        if: ${{ env.LABEL == 'Patch' }}
        run: npm version patch

      - name: Update Label for Minor
        if: ${{ env.LABEL == 'Minor' }}
        run: npm version minor

      - name: Update Label for Major
        if: ${{ env.LABEL == 'Major' }}
        run: npm version major

      - name: Setup the release version and overwrite the existing major version tag
        run: |
          git push